### ISSUE TITLE
Have a FieldGroup listen to its own changes

### ISSUE THREAD

**Issue by multimeric** [hanjinliu/magic-class#121]
I have a `FieldGroup`, and whenever any field within that group changes, I want to run a function. Here are some approaches I've tried.

Firstly, we can't use the decorator form `self.connect()` because self isn't defined within the class.

Secondly, I tried doing so in the constructor:
```python
from magicclass import FieldGroup, field

class Fields(FieldGroup):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.connect(self._changed)

    def _changed(self):
        print("Changed!")
    
    x = field(int)
    y = field(str)

Fields().show(run=True)
```
This doesn't seem to ever call `_changed`.

Lastly, if I instead use `self.changed.connect(self._changed)` in the constructor, it blocks the field group from listening to its child widget events.

How should I solve this?

**Comment by multimeric** [comment]
Okay, it seems that overriding `def _on_value_change(self, *args, **kwargs) -> None:` for the `FieldGroup` does work.

**Comment by hanjinliu** [comment]
Hi @multimeric ,
Just like other field objects, `FieldGroup` is supposed to be used as a class variable. Callbacks are connected via attribute access.

```python
from magicclass import FieldGroup, field

class Fields(FieldGroup):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.connect(self._changed)

    def _changed(self):
        print("Changed!")

    x = field(int)
    y = field(str)

class A:
    group = Fields()  # <--- as a field

a = A()
a.group.x.value = 4  # [Out:] Changed!
```

As usual for `Container`, you can use `self.changed.connect` instead of `self.connect` to immediately connect the callbacks.

But according to your example, it seems that `FieldGroup` is actually very useful as a simple container. Let me think more about that and I'll add some features including direct usage of `connect` 😄

**Comment by hanjinliu** [comment]
Hi @multimeric ,
I realized that using `self.connect` for the direct container usage is not a good idea. To use a field group as a class attribute, it is necessary to reconnect all the callbacks to the newly generated widget. If `self.connect` will connect the calback to `self` iteself, newly generated widget will be connect twice.

```python
class A(FieldGroup):
    a = field(int)
    def __init__(self):
        self.connect(self_some._callback)  # <-- if callback is connected to self...

class MyClass:
    group = A()

ui = MyClass()
ui.group  # <---- then, the same callback will be connected twice here.
```

I'll add more notes to the `connect` function to avoid this usage.
