### ISSUE TITLE
`Literal` type plus `RadioButtons

### ISSUE THREAD

**Issue by multimeric** [hanjinliu/magic-class#122]
When you combine a field with a `Literal` and the `RadioButtons` type, magicclass doesn't seem to render anything:

```python
from magicclass import magicclass, field
from typing import Literal

@magicclass
class Gui:
    foo = field(Literal["a", "b", "c"], widget_type="RadioButtons")
    
Gui().show(run=True)
```
<img width="99" alt="Screen Shot 2023-09-21 at 9 40 11 am" src="https://github.com/hanjinliu/magic-class/assets/5019367/748f6eb9-a01f-4224-88fa-e1231deded57">

**Comment by hanjinliu** [comment]
It seems to be a bug of magicgui.
I opened an issue [here](https://github.com/pyapp-kit/magicgui/issues/585).
