### ISSUE TITLE
Release 0.8.0

### ISSUE THREAD

**Issue by multimeric** [hanjinliu/magic-class#128]
Hi, I noticed you added compatibility for magicgui 0.8.0, but it isn't yet on PyPI. I think this means that installing the latest version of both libraries will fail (?)

**Comment by hanjinliu** [comment]
Hi, @multimeric ,
as far as I remember, change in the behavior of `parent` property of magicgui widgets breaks some part of the implementation of `magic-class`. `magicgui=0.8.0` with `magic-class<0.7.6` might be functional as a tool but even if it is, you may get some annoying GUI-related errors.

Thank you for reminding me of that, I think it's time to release.
