### ISSUE TITLE
"enabled" parameter

### ISSUE THREAD

**Issue by GiuseppeCiccone96** [hanjinliu/magic-class#15]
Enabled parameter does not seem to work as expected? For instance, in the code below I would expect the PushButton to display as disabled: 

```python
@magicclass
class Foo:
    a = field(PushButton,options={"enabled":False})

if __name__=="__main__":
    ui = Foo()
    ui.show()
```

however it displays as a clickable button: 
<img width="232" alt="Screenshot 2022-03-24 at 08 51 05" src="https://user-images.githubusercontent.com/72206039/159878595-7cd6c674-7541-4744-882f-f658529384ea.png">

is this behaviour expected?

**Comment by hanjinliu** [comment]
Hi @GiuseppeCiccone96 ,
That is definitely a bug. Thanks for reporting it!
