### ISSUE TITLE
`skip_if` not passed down in container hierarchies

### ISSUE THREAD

**Issue by bauerdavid** [hanjinliu/magic-class#155]
Hey @hanjinliu,
I wanted to use `magicclass.serialize.serialize()` to save widget states in a container, which contains nested containers. Some of these have Image widgets, and I wanted to skip these in serialization using the `skip_if` argument. The problem is that the value of `skip_if` is not passed down in the recursive call. I believe that adding it to lines 80 & 93 in `magicclass.serialize.py` would solve this issue.

**Comment by hanjinliu** [comment]
Hi @bauerdavid , thank you for reporting this issue!
Sorry for the late reply. I'll address this hopely in the next week.
