### ISSUE TITLE
Personalise Path widget

### ISSUE THREAD

**Issue by massimovassalli** [hanjinliu/magic-class#30]
Hi, this is a simple help request.
I was trying to customise the Path widget to either select multiple files (to open them) or even an entire folder. Do you have any suggestions on how to tweak the widget?
Thanks!

**Comment by hanjinliu** [comment]
Hi @massimovassalli ,

These are not `magic-class` feature but originally implemented in `magicgui`.

You can use type annotation `list[Path]` to open multiple files:

```python
@magicclass
class A:
    def f(self, paths: list[Path]):
        print(paths)
```

If you want to select a folder, you need to set `mode` option:

```python
@magicclass
class A:
    @set_options(path={"mode": "d"})
    def f(self, path: Path):
        print(paths)
```
