### ISSUE TITLE
callbacks in nested classes

### ISSUE THREAD

**Issue by pr4deepr** [hanjinliu/magic-class#4]
Hi
  I am trying to use callbacks within magicclass and running into errors.. 

When I try this, it works with no problem:
```
from magicclass import magicclass, vfield

@magicclass
class MyClass:
        a = vfield(int, options={"value": 30},name = "Deskew Angle")

        @a.connect
        def _callback(self):
            print("value changed!",self.a)
ui = MyClass()
ui.show()
```

However, when I use nested classes and try to use callbacks, I get an error:

from magicclass import magicclass, vfield

```
@magicclass
class MyClass:
    @magicclass
    class MyClass1:
        a = vfield(int, options={"value": 30},name = "Deskew Angle")

        @a.connect
        def _callback(self):
            print("value changed!",self.a)
ui = MyClass()
ui.show()
```

ERROR:

> ---------------------------------------------------------------------------
> ValueError                                Traceback (most recent call last)
> D:\Anaconda3\envs\llsz_py39\lib\site-packages\magicclass\gui\class_gui.py in _convert_attributes_into_widgets(self)
>     102                     # If MagicField is given by field() function.
> --> 103                     widget = self._create_widget_from_field(name, attr)
>     104 
> 
> D:\Anaconda3\envs\llsz_py39\lib\site-packages\magicclass\gui\class_gui.py in _create_widget_from_field(self, name, fld)
>      59                 # funcname = callback.__name__
> ---> 60                 widget.changed.connect(define_callback(self, callback))
>      61 
> 
> D:\Anaconda3\envs\llsz_py39\lib\site-packages\magicclass\gui\utils.py in define_callback(self, callback)
>      12 def define_callback(self: BaseGui, callback: Callable):
> ---> 13     clsname, funcname = callback.__qualname__.split(".")
>      14     def _callback():
> 
> ValueError: too many values to unpack (expected 2)
> 
> The above exception was the direct cause of the following exception:
> 
> MagicClassConstructionError               Traceback (most recent call last)
> ~\AppData\Local\Temp/ipykernel_23928/3118444370.py in <module>
>      10         def _callback(self):
>      11             print("value changed!",self.a)
> ---> 12 ui = MyClass()
>      13 ui.show()
> 
> D:\Anaconda3\envs\llsz_py39\lib\site-packages\magicclass\core.py in __init__(self, *args, **kwargs)
>     205                                )
>     206             super(oldclass, self).__init__(*args, **kwargs)
> --> 207             self._convert_attributes_into_widgets()
>     208 
>     209             if hasattr(self, _POST_INIT):
> 
> D:\Anaconda3\envs\llsz_py39\lib\site-packages\magicclass\gui\class_gui.py in _convert_attributes_into_widgets(self)
>     213                 if isinstance(e, MagicClassConstructionError):
>     214                     e.args = (f"\n{hist_str}\n{e}",)
> --> 215                     raise e
>     216                 else:
>     217                     raise MagicClassConstructionError(f"\n{hist_str}\n\n{type(e).__name__}: {e}") from e
> 
> D:\Anaconda3\envs\llsz_py39\lib\site-packages\magicclass\gui\class_gui.py in _convert_attributes_into_widgets(self)
>      92                 if isinstance(attr, type):
>      93                     # Nested magic-class
> ---> 94                     widget = attr()
>      95                     setattr(self, name, widget)
>      96 
> 
> D:\Anaconda3\envs\llsz_py39\lib\site-packages\magicclass\core.py in __init__(self, *args, **kwargs)
>     205                                )
>     206             super(oldclass, self).__init__(*args, **kwargs)
> --> 207             self._convert_attributes_into_widgets()
>     208 
>     209             if hasattr(self, _POST_INIT):
> 
> D:\Anaconda3\envs\llsz_py39\lib\site-packages\magicclass\gui\class_gui.py in _convert_attributes_into_widgets(self)
>     215                     raise e
>     216                 else:
> --> 217                     raise MagicClassConstructionError(f"\n{hist_str}\n\n{type(e).__name__}: {e}") from e
>     218 
>     219 
> 
> MagicClassConstructionError: 
> 
> 		MyClass1 (ABCMeta) <--- Error
> 
> 
> 		a (MagicValueField) <--- Error
> ValueError: too many values to unpack (expected 2)

I have the latest version of magicclass installed...
Is there an error with how I'm using this functionality??

Thanks
Pradeep

**Comment by hanjinliu** [comment]
Hi @pr4deepr,

That must be a bug ... thanks for reporting it!
I'll see what's wrong and let you know after it's solved.

Here's a quick fix for now:

```python
@magicclass
class MyClass:
    @magicclass
    class MyClass1:
        a = vfield(int, options={"value": 30},name = "Deskew Angle")

    @MyClass1.a.connect
    def _callback(self):
        print("value changed!",self.MyClass1.a)
ui = MyClass()
ui.show()
```

**Comment by hanjinliu** [comment]
Hi again,
I think it's fixed in the latest commit.
You can clone and try it if you'd like to.

**Comment by pr4deepr** [comment]
Hi
   Thanks, it works with the latest commit!

Cheers
Pradeep

**Comment by pr4deepr** [comment]
Thanks.. It works with the latest commit!
