### ISSUE TITLE
Table widget parameters and methods

### ISSUE THREAD

**Issue by GiuseppeCiccone96** [hanjinliu/magic-class#40]
Hi @hanjinliu, I have a Table widget in my magicclass GUI created using field. I would like to limit the maximum value (int or float) that can be entered in any of the table's cells. Also, I would like to update a plot embedded in the GUI every time any of the table's values is changed. 
I looked at the documentation of magicgui/magiclass but could not find info on this widget. 
Could you point at something regarding this? 
Thanks!

**Comment by hanjinliu** [comment]
Hi, @GiuseppeCiccone96 ,
do you mean the `Table` widget from `magicgui.widgets`? I think you can somehow do what you want by connecting a validation function or a function that updates the plot to the `changed` signal.

```python
@table.changed.connect
def _on_value_changed(info):
    # do anything
```

**Comment by GiuseppeCiccone96** [comment]
Hi @hanjinliu,
Yes, the ```Table``` widgets from ```magicgui.widgets```.
 When I do what you suggested, I get this error: 
```python 
AttributeError: 'MagicField' object has no attribute 'changed'
```

**Comment by hanjinliu** [comment]
How you should connect callbacks depends on whether you are handling a `Widget` or a `MagicField`.

```python
@magicclass
class A:
    a = field(int)
    a  # <- this is a MagicField
    def __init__(self):
        self.a  # <- this is a Widget
```

I think you tried to connect a callback to a `MagicField` (not a `Widget`). In that case, you should use the `connect` method of a `MagicField`.

```python
```

**Comment by GiuseppeCiccone96** [comment]
This works now. When I assign the ```Table``` widget value to a pandas ```DataFrame``` to display in the GUI, the callback is called for each value changed (as the default values of the ```Table``` widget are None). Do you know if there is a way to avoid this - and having the callback only for after the ```Table``` widget values have been assigned?

**Comment by hanjinliu** [comment]
I think you can avoid that by blocking the signal.

```python
with self.table.changed.blocked():
    self.table.value = df  # callback won't be called
```

**Comment by GiuseppeCiccone96** [comment]
That partially made it better, but I get the following error: 

```python 
TypeError: '>' not supported between instances of 'NoneType' and 'float'
Abort trap: 6
```
when running the following: 

```python
from magicclass import magicclass, field, set_design, Icon
from magicclass.widgets import Table
from pathlib import Path
import pandas as pd

@magicclass
class FluoPlate: 
  def __init__(self):
    self.plate=None
  @set_design(icon=Icon.ArrowUp, min_width=1, min_height=1,text="Load Existing Plate")
  def load_plate(self,path: Path):
    """
    Loads file containing desired plate intensities (.xlsx).
    """
    self.path=str(path)
    with self.plate_table.changed.blocked():
      self.plate = pd.read_excel(str(path),header=None)
      self.plate_table.value=self.plate
      self.plate_table.visible=True

  plate_table=field(Table,options={"visible":False})

  @plate_table.connect
  def _set_value_limit(self):
    max_value=1400.0
    data = self.plate_table.value["data"]
    for i in range(len(data)):
      for j in range(len(data[i])):
        if data[i][j] > max_value:
          data[i][j]=max_value
    data = pd.DataFrame(data)
    self.plate_table.value=data
```
test data: https://docs.google.com/spreadsheets/d/1ZV-p0eXUL7gWyGVKJ45WypCKe2Jpz1O5/edit?usp=sharing&ouid=103448787129633083904&rtpof=true&sd=true

**Comment by hanjinliu** [comment]
It's strange you do not get recursion error... the line `self.plate_table.value=data` should trigger another call of `_set_value_limit` (at least in my env) so you have to block the signal again. 

```python
with self.plate_table.changed.blocked():
    self.plate_table.value=data
```

For the TypeError you got, I think it is caused by an empty cell. Empty value will be converted into `None` in `magicgui` 's `Table`. Since `Table` widget is not type safe, I think it's better to check the type of the cell value before the evaluation of `data[i][j] > max_value`.
