### ISSUE TITLE
Trouble creating magic-class with two functions, each decorated with @magicgui

### ISSUE THREAD

**Issue by AlexCoul** [hanjinliu/magic-class#53]
We are updating some older magic-class code we used to control a microscope with napari. In the process, we discovered that our GUI is no longer being rendered correctly in napari. That led to some testing and questions on my part.

My main question is how do I create two functions in a magic-class, each decorator with magicgui options?

For example, I would expect this code,

```python
from magicclass import magicclass
from magicgui import magicgui

# Test magicgui options      
@magicclass(labels=False,name='Test two magicgui')
class TestTwoMagicgui:

    # initialize
    def __init__(self):
        self.value_1 = 25
        self.value_2 = 400
        self.value_3 = 0

    @magicgui(layout='horizontal',
              value_1={"widget_type": "FloatSpinBox", "min": 5, "max": 225, "label": 'Value 1'},
              call_button = 'Set value 1')
    def set_value_1(self, value_1 = 25.0):
        """
        Set value 1

        :param value_1: float

        :return None:
        """

        self.value_1=value_1

    @magicgui(layout='horizontal',
              value_2 = {"widget_type": "SpinBox",  "min": 0, "max": 100, "label": 'Value 2'},
              value_3 = {"widget_type": "FloatSpinBox", "min": 0.0, "max": 200.0, "label": 'Value 3'},
              call_button = "Set values 2 and 3"
             )
    def set_values_2_3(self, value_2= 50, value_3 = 10.0):
        """
        Set values 2 and 3

        :param value_2: int
        :param value_3: float

        :return None:
        """

        self.value_2 = value_2
        self.value_3 = value_3

if __name__ == "__main__":
    ui = TestTwoMagicgui()
    ui.show()
```

To show a GUI with two widgets. The first widget should have one entry and the second widget have two entries. Instead, I get a blank GUI that I have to expand to see the title of the window (screenshot attached).

![image](https://user-images.githubusercontent.com/23435837/198751425-9557cde0-02d6-47ca-a03b-3468817038db.png)

Do you have any suggestions about how to properly setup the above magic-class?

Thanks!

**Comment by hanjinliu** [comment]
It looks like a bug... @AlexCoul thank you for reporting it!
I found that the magicgui widgets are somehow invisible. I'll try to fix it later. 
As a workaround for now, you can manually set the visibility to make it work: `ui[set_value_1].visible = True`.

**Comment by AlexCoul** [comment]
Thank you, that worked!
