### ISSUE TITLE
`WidgetOptions` being removed

### ISSUE THREAD

**Issue by tlambert03** [hanjinliu/magic-class#59]
hey @hanjinliu, I removed `magicgui.types.WidgetOptions`, which you import in various places outside of a `TYPE_CHECKING` clause.

I can put it back in, but I would be doing so only to avoid breaking your stuff.  If you're just importing for the sake of type hints, I would recommend using:

```python
if TYPE_CHECKING:
    from magicgui.types import WidgetOptions
```

I see a number of other private imports (such as from `widgets._concrete`) and just wanted to give you a heads up that I would like to be reorganizing a number of things, most of which were private, and these will probably break some of your stuff.  You might be better off vendoring (i.e. copying into this repo) any of the private things that you would like to use here.

**Comment by tlambert03** [comment]
note also that `from magicgui._type_wrapper import resolve_annotation` no longer exists... So you should remove usage of it from your code too

**Comment by hanjinliu** [comment]
Hi @tlambert03 , thank you for notifying me!
I'll get around to it in a few days.

> I would like to be reorganizing a number of things, most of which were private, and these will probably break some of your stuff

Some of the private things, such as `ValueWidget`, are necessary for `isinstance` check and/or class inheritance, which means we (including all the users) still have to import them from `magicgui`. I'll add some try/except to avoid incompatibility, but I think it might be better to make them publically available, or future refactoring (if any?) will cause another confusion.

**Comment by tlambert03** [comment]
> Some of the private things, such as ValueWidget, are necessary for isinstance check and/or class inheritance, 

yep, I agree, `ValueWidget` should be public!
as you run into other things that feel like they should be public, take note of them and we'll make sure they're available
